################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../fftw3-master/kernel/align.c \
../fftw3-master/kernel/alloc.c \
../fftw3-master/kernel/assert.c \
../fftw3-master/kernel/awake.c \
../fftw3-master/kernel/buffered.c \
../fftw3-master/kernel/cpy1d.c \
../fftw3-master/kernel/cpy2d-pair.c \
../fftw3-master/kernel/cpy2d.c \
../fftw3-master/kernel/ct.c \
../fftw3-master/kernel/debug.c \
../fftw3-master/kernel/extract-reim.c \
../fftw3-master/kernel/hash.c \
../fftw3-master/kernel/iabs.c \
../fftw3-master/kernel/kalloc.c \
../fftw3-master/kernel/md5-1.c \
../fftw3-master/kernel/md5.c \
../fftw3-master/kernel/minmax.c \
../fftw3-master/kernel/ops.c \
../fftw3-master/kernel/pickdim.c \
../fftw3-master/kernel/plan.c \
../fftw3-master/kernel/planner.c \
../fftw3-master/kernel/primes.c \
../fftw3-master/kernel/print.c \
../fftw3-master/kernel/problem.c \
../fftw3-master/kernel/rader.c \
../fftw3-master/kernel/scan.c \
../fftw3-master/kernel/solver.c \
../fftw3-master/kernel/solvtab.c \
../fftw3-master/kernel/stride.c \
../fftw3-master/kernel/tensor.c \
../fftw3-master/kernel/tensor1.c \
../fftw3-master/kernel/tensor2.c \
../fftw3-master/kernel/tensor3.c \
../fftw3-master/kernel/tensor4.c \
../fftw3-master/kernel/tensor5.c \
../fftw3-master/kernel/tensor7.c \
../fftw3-master/kernel/tensor8.c \
../fftw3-master/kernel/tensor9.c \
../fftw3-master/kernel/tile2d.c \
../fftw3-master/kernel/timer.c \
../fftw3-master/kernel/transpose.c \
../fftw3-master/kernel/trig.c \
../fftw3-master/kernel/twiddle.c 

OBJS += \
./align.obj \
./alloc.obj \
./assert.obj \
./awake.obj \
./cpy1d.obj \
./cpy2d-pair.obj \
./cpy2d.obj \
./ct.obj \
./debug.obj \
./extract-reim.obj \
./hash.obj \
./iabs.obj \
./kalloc.obj \
./md5-1.obj \
./md5.obj \
./minmax.obj \
./ops.obj \
./pickdim.obj \
./planner.obj \
./primes.obj \
./print.obj \
./rader.obj \
./scan.obj \
./solver.obj \
./solvtab.obj \
./stride.obj \
./tensor.obj \
./tensor1.obj \
./tensor2.obj \
./tensor3.obj \
./tensor4.obj \
./tensor5.obj \
./tensor7.obj \
./tensor8.obj \
./tensor9.obj \
./tile2d.obj \
./timer.obj \
./transpose.obj \
./trig.obj \
./twiddle.obj 

C_DEPS += \
./fftw3-master/kernel/align.pp \
./fftw3-master/kernel/alloc.pp \
./fftw3-master/kernel/assert.pp \
./fftw3-master/kernel/awake.pp \
./fftw3-master/kernel/buffered.pp \
./fftw3-master/kernel/cpy1d.pp \
./fftw3-master/kernel/cpy2d-pair.pp \
./fftw3-master/kernel/cpy2d.pp \
./fftw3-master/kernel/ct.pp \
./fftw3-master/kernel/debug.pp \
./fftw3-master/kernel/extract-reim.pp \
./fftw3-master/kernel/hash.pp \
./fftw3-master/kernel/iabs.pp \
./fftw3-master/kernel/kalloc.pp \
./fftw3-master/kernel/md5-1.pp \
./fftw3-master/kernel/md5.pp \
./fftw3-master/kernel/minmax.pp \
./fftw3-master/kernel/ops.pp \
./fftw3-master/kernel/pickdim.pp \
./fftw3-master/kernel/plan.pp \
./fftw3-master/kernel/planner.pp \
./fftw3-master/kernel/primes.pp \
./fftw3-master/kernel/print.pp \
./fftw3-master/kernel/problem.pp \
./fftw3-master/kernel/rader.pp \
./fftw3-master/kernel/scan.pp \
./fftw3-master/kernel/solver.pp \
./fftw3-master/kernel/solvtab.pp \
./fftw3-master/kernel/stride.pp \
./fftw3-master/kernel/tensor.pp \
./fftw3-master/kernel/tensor1.pp \
./fftw3-master/kernel/tensor2.pp \
./fftw3-master/kernel/tensor3.pp \
./fftw3-master/kernel/tensor4.pp \
./fftw3-master/kernel/tensor5.pp \
./fftw3-master/kernel/tensor7.pp \
./fftw3-master/kernel/tensor8.pp \
./fftw3-master/kernel/tensor9.pp \
./fftw3-master/kernel/tile2d.pp \
./fftw3-master/kernel/timer.pp \
./fftw3-master/kernel/transpose.pp \
./fftw3-master/kernel/trig.pp \
./fftw3-master/kernel/twiddle.pp 

C_DEPS__QUOTED += \
"fftw3-master\kernel\align.pp" \
"fftw3-master\kernel\alloc.pp" \
"fftw3-master\kernel\assert.pp" \
"fftw3-master\kernel\awake.pp" \
"fftw3-master\kernel\buffered.pp" \
"fftw3-master\kernel\cpy1d.pp" \
"fftw3-master\kernel\cpy2d-pair.pp" \
"fftw3-master\kernel\cpy2d.pp" \
"fftw3-master\kernel\ct.pp" \
"fftw3-master\kernel\debug.pp" \
"fftw3-master\kernel\extract-reim.pp" \
"fftw3-master\kernel\hash.pp" \
"fftw3-master\kernel\iabs.pp" \
"fftw3-master\kernel\kalloc.pp" \
"fftw3-master\kernel\md5-1.pp" \
"fftw3-master\kernel\md5.pp" \
"fftw3-master\kernel\minmax.pp" \
"fftw3-master\kernel\ops.pp" \
"fftw3-master\kernel\pickdim.pp" \
"fftw3-master\kernel\plan.pp" \
"fftw3-master\kernel\planner.pp" \
"fftw3-master\kernel\primes.pp" \
"fftw3-master\kernel\print.pp" \
"fftw3-master\kernel\problem.pp" \
"fftw3-master\kernel\rader.pp" \
"fftw3-master\kernel\scan.pp" \
"fftw3-master\kernel\solver.pp" \
"fftw3-master\kernel\solvtab.pp" \
"fftw3-master\kernel\stride.pp" \
"fftw3-master\kernel\tensor.pp" \
"fftw3-master\kernel\tensor1.pp" \
"fftw3-master\kernel\tensor2.pp" \
"fftw3-master\kernel\tensor3.pp" \
"fftw3-master\kernel\tensor4.pp" \
"fftw3-master\kernel\tensor5.pp" \
"fftw3-master\kernel\tensor7.pp" \
"fftw3-master\kernel\tensor8.pp" \
"fftw3-master\kernel\tensor9.pp" \
"fftw3-master\kernel\tile2d.pp" \
"fftw3-master\kernel\timer.pp" \
"fftw3-master\kernel\transpose.pp" \
"fftw3-master\kernel\trig.pp" \
"fftw3-master\kernel\twiddle.pp" 

OBJS__QUOTED += \
"align.obj" \
"alloc.obj" \
"assert.obj" \
"awake.obj" \
"cpy1d.obj" \
"cpy2d-pair.obj" \
"cpy2d.obj" \
"ct.obj" \
"debug.obj" \
"extract-reim.obj" \
"hash.obj" \
"iabs.obj" \
"kalloc.obj" \
"md5-1.obj" \
"md5.obj" \
"minmax.obj" \
"ops.obj" \
"pickdim.obj" \
"planner.obj" \
"primes.obj" \
"print.obj" \
"rader.obj" \
"scan.obj" \
"solver.obj" \
"solvtab.obj" \
"stride.obj" \
"tensor.obj" \
"tensor1.obj" \
"tensor2.obj" \
"tensor3.obj" \
"tensor4.obj" \
"tensor5.obj" \
"tensor7.obj" \
"tensor8.obj" \
"tensor9.obj" \
"tile2d.obj" \
"timer.obj" \
"transpose.obj" \
"trig.obj" \
"twiddle.obj" 

C_SRCS__QUOTED += \
"../fftw3-master/kernel/align.c" \
"../fftw3-master/kernel/alloc.c" \
"../fftw3-master/kernel/assert.c" \
"../fftw3-master/kernel/awake.c" \
"../fftw3-master/kernel/buffered.c" \
"../fftw3-master/kernel/cpy1d.c" \
"../fftw3-master/kernel/cpy2d-pair.c" \
"../fftw3-master/kernel/cpy2d.c" \
"../fftw3-master/kernel/ct.c" \
"../fftw3-master/kernel/debug.c" \
"../fftw3-master/kernel/extract-reim.c" \
"../fftw3-master/kernel/hash.c" \
"../fftw3-master/kernel/iabs.c" \
"../fftw3-master/kernel/kalloc.c" \
"../fftw3-master/kernel/md5-1.c" \
"../fftw3-master/kernel/md5.c" \
"../fftw3-master/kernel/minmax.c" \
"../fftw3-master/kernel/ops.c" \
"../fftw3-master/kernel/pickdim.c" \
"../fftw3-master/kernel/plan.c" \
"../fftw3-master/kernel/planner.c" \
"../fftw3-master/kernel/primes.c" \
"../fftw3-master/kernel/print.c" \
"../fftw3-master/kernel/problem.c" \
"../fftw3-master/kernel/rader.c" \
"../fftw3-master/kernel/scan.c" \
"../fftw3-master/kernel/solver.c" \
"../fftw3-master/kernel/solvtab.c" \
"../fftw3-master/kernel/stride.c" \
"../fftw3-master/kernel/tensor.c" \
"../fftw3-master/kernel/tensor1.c" \
"../fftw3-master/kernel/tensor2.c" \
"../fftw3-master/kernel/tensor3.c" \
"../fftw3-master/kernel/tensor4.c" \
"../fftw3-master/kernel/tensor5.c" \
"../fftw3-master/kernel/tensor7.c" \
"../fftw3-master/kernel/tensor8.c" \
"../fftw3-master/kernel/tensor9.c" \
"../fftw3-master/kernel/tile2d.c" \
"../fftw3-master/kernel/timer.c" \
"../fftw3-master/kernel/transpose.c" \
"../fftw3-master/kernel/trig.c" \
"../fftw3-master/kernel/twiddle.c" 


