################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../fftw3-master/api/apiplan.c \
../fftw3-master/api/configure.c \
../fftw3-master/api/execute-dft-c2r.c \
../fftw3-master/api/execute-dft-r2c.c \
../fftw3-master/api/execute-dft.c \
../fftw3-master/api/execute-r2r.c \
../fftw3-master/api/execute-split-dft-c2r.c \
../fftw3-master/api/execute-split-dft-r2c.c \
../fftw3-master/api/execute-split-dft.c \
../fftw3-master/api/execute.c \
../fftw3-master/api/export-wisdom-to-file.c \
../fftw3-master/api/export-wisdom-to-string.c \
../fftw3-master/api/export-wisdom.c \
../fftw3-master/api/f77api.c \
../fftw3-master/api/flops.c \
../fftw3-master/api/forget-wisdom.c \
../fftw3-master/api/import-system-wisdom.c \
../fftw3-master/api/import-wisdom-from-file.c \
../fftw3-master/api/import-wisdom-from-string.c \
../fftw3-master/api/import-wisdom.c \
../fftw3-master/api/malloc.c \
../fftw3-master/api/map-r2r-kind.c \
../fftw3-master/api/mapflags.c \
../fftw3-master/api/mkprinter-file.c \
../fftw3-master/api/mkprinter-str.c \
../fftw3-master/api/mktensor-iodims.c \
../fftw3-master/api/mktensor-iodims64.c \
../fftw3-master/api/mktensor-rowmajor.c \
../fftw3-master/api/plan-dft-1d.c \
../fftw3-master/api/plan-dft-2d.c \
../fftw3-master/api/plan-dft-3d.c \
../fftw3-master/api/plan-dft-c2r-1d.c \
../fftw3-master/api/plan-dft-c2r-2d.c \
../fftw3-master/api/plan-dft-c2r-3d.c \
../fftw3-master/api/plan-dft-c2r.c \
../fftw3-master/api/plan-dft-r2c-1d.c \
../fftw3-master/api/plan-dft-r2c-2d.c \
../fftw3-master/api/plan-dft-r2c-3d.c \
../fftw3-master/api/plan-dft-r2c.c \
../fftw3-master/api/plan-dft.c \
../fftw3-master/api/plan-guru-dft-c2r.c \
../fftw3-master/api/plan-guru-dft-r2c.c \
../fftw3-master/api/plan-guru-dft.c \
../fftw3-master/api/plan-guru-r2r.c \
../fftw3-master/api/plan-guru-split-dft-c2r.c \
../fftw3-master/api/plan-guru-split-dft-r2c.c \
../fftw3-master/api/plan-guru-split-dft.c \
../fftw3-master/api/plan-guru64-dft-c2r.c \
../fftw3-master/api/plan-guru64-dft-r2c.c \
../fftw3-master/api/plan-guru64-dft.c \
../fftw3-master/api/plan-guru64-r2r.c \
../fftw3-master/api/plan-guru64-split-dft-c2r.c \
../fftw3-master/api/plan-guru64-split-dft-r2c.c \
../fftw3-master/api/plan-guru64-split-dft.c \
../fftw3-master/api/plan-many-dft-c2r.c \
../fftw3-master/api/plan-many-dft-r2c.c \
../fftw3-master/api/plan-many-dft.c \
../fftw3-master/api/plan-many-r2r.c \
../fftw3-master/api/plan-r2r-1d.c \
../fftw3-master/api/plan-r2r-2d.c \
../fftw3-master/api/plan-r2r-3d.c \
../fftw3-master/api/plan-r2r.c \
../fftw3-master/api/print-plan.c \
../fftw3-master/api/rdft2-pad.c \
../fftw3-master/api/the-planner.c \
../fftw3-master/api/version.c 

OBJS += \
./apiplan.obj \
./configure.obj \
./execute-dft-c2r.obj \
./execute-dft-r2c.obj \
./execute-dft.obj \
./execute-r2r.obj \
./execute-split-dft-c2r.obj \
./execute-split-dft-r2c.obj \
./execute-split-dft.obj \
./execute.obj \
./export-wisdom-to-file.obj \
./export-wisdom-to-string.obj \
./export-wisdom.obj \
./f77api.obj \
./flops.obj \
./forget-wisdom.obj \
./import-system-wisdom.obj \
./import-wisdom-from-file.obj \
./import-wisdom-from-string.obj \
./import-wisdom.obj \
./malloc.obj \
./map-r2r-kind.obj \
./mapflags.obj \
./mkprinter-file.obj \
./mkprinter-str.obj \
./mktensor-iodims.obj \
./mktensor-iodims64.obj \
./mktensor-rowmajor.obj \
./plan-dft-1d.obj \
./plan-dft-2d.obj \
./plan-dft-3d.obj \
./plan-dft-c2r-1d.obj \
./plan-dft-c2r-2d.obj \
./plan-dft-c2r-3d.obj \
./plan-dft-c2r.obj \
./plan-dft-r2c-1d.obj \
./plan-dft-r2c-2d.obj \
./plan-dft-r2c-3d.obj \
./plan-dft-r2c.obj \
./plan-dft.obj \
./plan-guru-dft-c2r.obj \
./plan-guru-dft-r2c.obj \
./plan-guru-dft.obj \
./plan-guru-r2r.obj \
./plan-guru-split-dft-c2r.obj \
./plan-guru-split-dft-r2c.obj \
./plan-guru-split-dft.obj \
./plan-guru64-dft-c2r.obj \
./plan-guru64-dft-r2c.obj \
./plan-guru64-dft.obj \
./plan-guru64-r2r.obj \
./plan-guru64-split-dft-c2r.obj \
./plan-guru64-split-dft-r2c.obj \
./plan-guru64-split-dft.obj \
./plan-many-dft-c2r.obj \
./plan-many-dft-r2c.obj \
./plan-many-dft.obj \
./plan-many-r2r.obj \
./plan-r2r-1d.obj \
./plan-r2r-2d.obj \
./plan-r2r-3d.obj \
./plan-r2r.obj \
./print-plan.obj \
./rdft2-pad.obj \
./the-planner.obj \
./version.obj 

C_DEPS += \
./fftw3-master/api/apiplan.pp \
./fftw3-master/api/configure.pp \
./fftw3-master/api/execute-dft-c2r.pp \
./fftw3-master/api/execute-dft-r2c.pp \
./fftw3-master/api/execute-dft.pp \
./fftw3-master/api/execute-r2r.pp \
./fftw3-master/api/execute-split-dft-c2r.pp \
./fftw3-master/api/execute-split-dft-r2c.pp \
./fftw3-master/api/execute-split-dft.pp \
./fftw3-master/api/execute.pp \
./fftw3-master/api/export-wisdom-to-file.pp \
./fftw3-master/api/export-wisdom-to-string.pp \
./fftw3-master/api/export-wisdom.pp \
./fftw3-master/api/f77api.pp \
./fftw3-master/api/flops.pp \
./fftw3-master/api/forget-wisdom.pp \
./fftw3-master/api/import-system-wisdom.pp \
./fftw3-master/api/import-wisdom-from-file.pp \
./fftw3-master/api/import-wisdom-from-string.pp \
./fftw3-master/api/import-wisdom.pp \
./fftw3-master/api/malloc.pp \
./fftw3-master/api/map-r2r-kind.pp \
./fftw3-master/api/mapflags.pp \
./fftw3-master/api/mkprinter-file.pp \
./fftw3-master/api/mkprinter-str.pp \
./fftw3-master/api/mktensor-iodims.pp \
./fftw3-master/api/mktensor-iodims64.pp \
./fftw3-master/api/mktensor-rowmajor.pp \
./fftw3-master/api/plan-dft-1d.pp \
./fftw3-master/api/plan-dft-2d.pp \
./fftw3-master/api/plan-dft-3d.pp \
./fftw3-master/api/plan-dft-c2r-1d.pp \
./fftw3-master/api/plan-dft-c2r-2d.pp \
./fftw3-master/api/plan-dft-c2r-3d.pp \
./fftw3-master/api/plan-dft-c2r.pp \
./fftw3-master/api/plan-dft-r2c-1d.pp \
./fftw3-master/api/plan-dft-r2c-2d.pp \
./fftw3-master/api/plan-dft-r2c-3d.pp \
./fftw3-master/api/plan-dft-r2c.pp \
./fftw3-master/api/plan-dft.pp \
./fftw3-master/api/plan-guru-dft-c2r.pp \
./fftw3-master/api/plan-guru-dft-r2c.pp \
./fftw3-master/api/plan-guru-dft.pp \
./fftw3-master/api/plan-guru-r2r.pp \
./fftw3-master/api/plan-guru-split-dft-c2r.pp \
./fftw3-master/api/plan-guru-split-dft-r2c.pp \
./fftw3-master/api/plan-guru-split-dft.pp \
./fftw3-master/api/plan-guru64-dft-c2r.pp \
./fftw3-master/api/plan-guru64-dft-r2c.pp \
./fftw3-master/api/plan-guru64-dft.pp \
./fftw3-master/api/plan-guru64-r2r.pp \
./fftw3-master/api/plan-guru64-split-dft-c2r.pp \
./fftw3-master/api/plan-guru64-split-dft-r2c.pp \
./fftw3-master/api/plan-guru64-split-dft.pp \
./fftw3-master/api/plan-many-dft-c2r.pp \
./fftw3-master/api/plan-many-dft-r2c.pp \
./fftw3-master/api/plan-many-dft.pp \
./fftw3-master/api/plan-many-r2r.pp \
./fftw3-master/api/plan-r2r-1d.pp \
./fftw3-master/api/plan-r2r-2d.pp \
./fftw3-master/api/plan-r2r-3d.pp \
./fftw3-master/api/plan-r2r.pp \
./fftw3-master/api/print-plan.pp \
./fftw3-master/api/rdft2-pad.pp \
./fftw3-master/api/the-planner.pp \
./fftw3-master/api/version.pp 

C_DEPS__QUOTED += \
"fftw3-master\api\apiplan.pp" \
"fftw3-master\api\configure.pp" \
"fftw3-master\api\execute-dft-c2r.pp" \
"fftw3-master\api\execute-dft-r2c.pp" \
"fftw3-master\api\execute-dft.pp" \
"fftw3-master\api\execute-r2r.pp" \
"fftw3-master\api\execute-split-dft-c2r.pp" \
"fftw3-master\api\execute-split-dft-r2c.pp" \
"fftw3-master\api\execute-split-dft.pp" \
"fftw3-master\api\execute.pp" \
"fftw3-master\api\export-wisdom-to-file.pp" \
"fftw3-master\api\export-wisdom-to-string.pp" \
"fftw3-master\api\export-wisdom.pp" \
"fftw3-master\api\f77api.pp" \
"fftw3-master\api\flops.pp" \
"fftw3-master\api\forget-wisdom.pp" \
"fftw3-master\api\import-system-wisdom.pp" \
"fftw3-master\api\import-wisdom-from-file.pp" \
"fftw3-master\api\import-wisdom-from-string.pp" \
"fftw3-master\api\import-wisdom.pp" \
"fftw3-master\api\malloc.pp" \
"fftw3-master\api\map-r2r-kind.pp" \
"fftw3-master\api\mapflags.pp" \
"fftw3-master\api\mkprinter-file.pp" \
"fftw3-master\api\mkprinter-str.pp" \
"fftw3-master\api\mktensor-iodims.pp" \
"fftw3-master\api\mktensor-iodims64.pp" \
"fftw3-master\api\mktensor-rowmajor.pp" \
"fftw3-master\api\plan-dft-1d.pp" \
"fftw3-master\api\plan-dft-2d.pp" \
"fftw3-master\api\plan-dft-3d.pp" \
"fftw3-master\api\plan-dft-c2r-1d.pp" \
"fftw3-master\api\plan-dft-c2r-2d.pp" \
"fftw3-master\api\plan-dft-c2r-3d.pp" \
"fftw3-master\api\plan-dft-c2r.pp" \
"fftw3-master\api\plan-dft-r2c-1d.pp" \
"fftw3-master\api\plan-dft-r2c-2d.pp" \
"fftw3-master\api\plan-dft-r2c-3d.pp" \
"fftw3-master\api\plan-dft-r2c.pp" \
"fftw3-master\api\plan-dft.pp" \
"fftw3-master\api\plan-guru-dft-c2r.pp" \
"fftw3-master\api\plan-guru-dft-r2c.pp" \
"fftw3-master\api\plan-guru-dft.pp" \
"fftw3-master\api\plan-guru-r2r.pp" \
"fftw3-master\api\plan-guru-split-dft-c2r.pp" \
"fftw3-master\api\plan-guru-split-dft-r2c.pp" \
"fftw3-master\api\plan-guru-split-dft.pp" \
"fftw3-master\api\plan-guru64-dft-c2r.pp" \
"fftw3-master\api\plan-guru64-dft-r2c.pp" \
"fftw3-master\api\plan-guru64-dft.pp" \
"fftw3-master\api\plan-guru64-r2r.pp" \
"fftw3-master\api\plan-guru64-split-dft-c2r.pp" \
"fftw3-master\api\plan-guru64-split-dft-r2c.pp" \
"fftw3-master\api\plan-guru64-split-dft.pp" \
"fftw3-master\api\plan-many-dft-c2r.pp" \
"fftw3-master\api\plan-many-dft-r2c.pp" \
"fftw3-master\api\plan-many-dft.pp" \
"fftw3-master\api\plan-many-r2r.pp" \
"fftw3-master\api\plan-r2r-1d.pp" \
"fftw3-master\api\plan-r2r-2d.pp" \
"fftw3-master\api\plan-r2r-3d.pp" \
"fftw3-master\api\plan-r2r.pp" \
"fftw3-master\api\print-plan.pp" \
"fftw3-master\api\rdft2-pad.pp" \
"fftw3-master\api\the-planner.pp" \
"fftw3-master\api\version.pp" 

OBJS__QUOTED += \
"apiplan.obj" \
"configure.obj" \
"execute-dft-c2r.obj" \
"execute-dft-r2c.obj" \
"execute-dft.obj" \
"execute-r2r.obj" \
"execute-split-dft-c2r.obj" \
"execute-split-dft-r2c.obj" \
"execute-split-dft.obj" \
"execute.obj" \
"export-wisdom-to-file.obj" \
"export-wisdom-to-string.obj" \
"export-wisdom.obj" \
"f77api.obj" \
"flops.obj" \
"forget-wisdom.obj" \
"import-system-wisdom.obj" \
"import-wisdom-from-file.obj" \
"import-wisdom-from-string.obj" \
"import-wisdom.obj" \
"malloc.obj" \
"map-r2r-kind.obj" \
"mapflags.obj" \
"mkprinter-file.obj" \
"mkprinter-str.obj" \
"mktensor-iodims.obj" \
"mktensor-iodims64.obj" \
"mktensor-rowmajor.obj" \
"plan-dft-1d.obj" \
"plan-dft-2d.obj" \
"plan-dft-3d.obj" \
"plan-dft-c2r-1d.obj" \
"plan-dft-c2r-2d.obj" \
"plan-dft-c2r-3d.obj" \
"plan-dft-c2r.obj" \
"plan-dft-r2c-1d.obj" \
"plan-dft-r2c-2d.obj" \
"plan-dft-r2c-3d.obj" \
"plan-dft-r2c.obj" \
"plan-dft.obj" \
"plan-guru-dft-c2r.obj" \
"plan-guru-dft-r2c.obj" \
"plan-guru-dft.obj" \
"plan-guru-r2r.obj" \
"plan-guru-split-dft-c2r.obj" \
"plan-guru-split-dft-r2c.obj" \
"plan-guru-split-dft.obj" \
"plan-guru64-dft-c2r.obj" \
"plan-guru64-dft-r2c.obj" \
"plan-guru64-dft.obj" \
"plan-guru64-r2r.obj" \
"plan-guru64-split-dft-c2r.obj" \
"plan-guru64-split-dft-r2c.obj" \
"plan-guru64-split-dft.obj" \
"plan-many-dft-c2r.obj" \
"plan-many-dft-r2c.obj" \
"plan-many-dft.obj" \
"plan-many-r2r.obj" \
"plan-r2r-1d.obj" \
"plan-r2r-2d.obj" \
"plan-r2r-3d.obj" \
"plan-r2r.obj" \
"print-plan.obj" \
"rdft2-pad.obj" \
"the-planner.obj" \
"version.obj" 

C_SRCS__QUOTED += \
"../fftw3-master/api/apiplan.c" \
"../fftw3-master/api/configure.c" \
"../fftw3-master/api/execute-dft-c2r.c" \
"../fftw3-master/api/execute-dft-r2c.c" \
"../fftw3-master/api/execute-dft.c" \
"../fftw3-master/api/execute-r2r.c" \
"../fftw3-master/api/execute-split-dft-c2r.c" \
"../fftw3-master/api/execute-split-dft-r2c.c" \
"../fftw3-master/api/execute-split-dft.c" \
"../fftw3-master/api/execute.c" \
"../fftw3-master/api/export-wisdom-to-file.c" \
"../fftw3-master/api/export-wisdom-to-string.c" \
"../fftw3-master/api/export-wisdom.c" \
"../fftw3-master/api/f77api.c" \
"../fftw3-master/api/flops.c" \
"../fftw3-master/api/forget-wisdom.c" \
"../fftw3-master/api/import-system-wisdom.c" \
"../fftw3-master/api/import-wisdom-from-file.c" \
"../fftw3-master/api/import-wisdom-from-string.c" \
"../fftw3-master/api/import-wisdom.c" \
"../fftw3-master/api/malloc.c" \
"../fftw3-master/api/map-r2r-kind.c" \
"../fftw3-master/api/mapflags.c" \
"../fftw3-master/api/mkprinter-file.c" \
"../fftw3-master/api/mkprinter-str.c" \
"../fftw3-master/api/mktensor-iodims.c" \
"../fftw3-master/api/mktensor-iodims64.c" \
"../fftw3-master/api/mktensor-rowmajor.c" \
"../fftw3-master/api/plan-dft-1d.c" \
"../fftw3-master/api/plan-dft-2d.c" \
"../fftw3-master/api/plan-dft-3d.c" \
"../fftw3-master/api/plan-dft-c2r-1d.c" \
"../fftw3-master/api/plan-dft-c2r-2d.c" \
"../fftw3-master/api/plan-dft-c2r-3d.c" \
"../fftw3-master/api/plan-dft-c2r.c" \
"../fftw3-master/api/plan-dft-r2c-1d.c" \
"../fftw3-master/api/plan-dft-r2c-2d.c" \
"../fftw3-master/api/plan-dft-r2c-3d.c" \
"../fftw3-master/api/plan-dft-r2c.c" \
"../fftw3-master/api/plan-dft.c" \
"../fftw3-master/api/plan-guru-dft-c2r.c" \
"../fftw3-master/api/plan-guru-dft-r2c.c" \
"../fftw3-master/api/plan-guru-dft.c" \
"../fftw3-master/api/plan-guru-r2r.c" \
"../fftw3-master/api/plan-guru-split-dft-c2r.c" \
"../fftw3-master/api/plan-guru-split-dft-r2c.c" \
"../fftw3-master/api/plan-guru-split-dft.c" \
"../fftw3-master/api/plan-guru64-dft-c2r.c" \
"../fftw3-master/api/plan-guru64-dft-r2c.c" \
"../fftw3-master/api/plan-guru64-dft.c" \
"../fftw3-master/api/plan-guru64-r2r.c" \
"../fftw3-master/api/plan-guru64-split-dft-c2r.c" \
"../fftw3-master/api/plan-guru64-split-dft-r2c.c" \
"../fftw3-master/api/plan-guru64-split-dft.c" \
"../fftw3-master/api/plan-many-dft-c2r.c" \
"../fftw3-master/api/plan-many-dft-r2c.c" \
"../fftw3-master/api/plan-many-dft.c" \
"../fftw3-master/api/plan-many-r2r.c" \
"../fftw3-master/api/plan-r2r-1d.c" \
"../fftw3-master/api/plan-r2r-2d.c" \
"../fftw3-master/api/plan-r2r-3d.c" \
"../fftw3-master/api/plan-r2r.c" \
"../fftw3-master/api/print-plan.c" \
"../fftw3-master/api/rdft2-pad.c" \
"../fftw3-master/api/the-planner.c" \
"../fftw3-master/api/version.c" 


